---
language: minimal

dist: focal

services:
  - docker

script:
  - bash test-in-docker.sh

deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_TOKEN
  on:
    branch: master

# vim: set sw=2:
