---
version: '3.6'

services:
    test-runner:
        image: ${uniq_test_id:-djifxvault}:test-runner
        build:
            context: .
            dockerfile: Dockerfile.testing
        environment:
            INFORMIXDIR: /opt/IBM/informix
            INFORMIXSQLHOSTS: /opt/IBM/informix/etc/sqlhosts
            LD_LIBRARY_PATH: /opt/IBM/informix/lib:/opt/IBM/informix/lib/cli:/opt/IBM/informix/lib/esql
        volumes:
            - type: bind
              source: ./docker-compose.sqlhosts
              target: /opt/IBM/informix/etc/sqlhosts
        depends_on:
            - db
            - vault
        networks:
            - test
        links:
            - db:informix
            - vault
    db:
        image: ibmcom/informix-developer-database:${ifx_version:-14.10.FC3DE}
        tty: true  # Needed to ensure container doesn't self terminate
        hostname: db
        environment:
            LICENSE: accept
            DB_USER: adapter
            DB_NAME: adapter
            DB_PASS: adapter
        privileged: true
        networks:
            - test
        ports:
            - "9088:9088"
            - "9089:9089"
            - "27017:27017"
            - "27018:27018"
            - "27883:27883"
    vault:
        image: vault:${vault_version:-1.4.2}
        hostname: vault
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: 'test-token'
        networks:
            - test
        ports:
            - "8200:8200"

networks:
    test:
        name: ${uniq_test_id:-djifxivault}

# vim: set sw=4:
